FROM mongo:4.4 AS staging-mongo

COPY infrastructure/staging-mongo/entrypoint.sh /usr/local/bin/cukies-staging-mongo-entrypoint
COPY infrastructure/staging-mongo/resync.sh /usr/local/bin/cukies-staging-mongo-resync

RUN chmod 0755 \
  /usr/local/bin/cukies-staging-mongo-entrypoint \
  /usr/local/bin/cukies-staging-mongo-resync

ENTRYPOINT ["/usr/local/bin/cukies-staging-mongo-entrypoint"]

FROM node:22-bookworm-slim AS app

ARG CUKIES_SERVICE=dapp
ARG NEXT_PUBLIC_APP_ENV
ARG NEXT_PUBLIC_UKI_CHAIN_ID
ARG NEXT_PUBLIC_ASM_TOKEN_ADDRESS
ARG NEXT_PUBLIC_UKI_TOKEN_ADDRESS
ARG NEXT_PUBLIC_UKI_VESTING_VAULT_ADDRESS
ARG NEXT_PUBLIC_UKI_PRESALE_ADDRESS
ARG NEXT_PUBLIC_UKI_STAKING_ADDRESS
ARG NEXT_PUBLIC_UKI_REWARDS_DISTRIBUTOR_ADDRESS
ARG NEXT_PUBLIC_UKI_LIQUIDITY_PAIR_ADDRESS
ARG NEXT_PUBLIC_UKI_LIQUIDITY_LOCKER_ADDRESS
ARG NEXT_PUBLIC_UKI_LIQUIDITY_UNLOCK_LABEL
ARG NEXT_PUBLIC_UKI_SWAP_URL
ARG NEXT_PUBLIC_CUKIE_MASTER_NFT_VAULT_ADDRESS
ARG NEXT_PUBLIC_CUKIE_POOL_NFT_VAULT_ADDRESS
ARG NEXT_PUBLIC_CUKIES_NFT_COLLECTION_ADDRESS
ARG NEXT_PUBLIC_CUKIES_NFT_COLLECTION_ADDRESSES
ARG NEXT_PUBLIC_CUKIES_NFT_RECOVERY_COLLECTION_ADDRESSES
ARG NEXT_PUBLIC_CUKIES_BRIDGE_MODE
ARG NEXT_PUBLIC_CUKIES_BRIDGE_BSC_CHAIN_ID
ARG NEXT_PUBLIC_CUKIES_BRIDGE_BSC_COLLECTION_ADDRESS
ARG NEXT_PUBLIC_CUKIES_BRIDGE_BSC_ENDPOINT_ADDRESS
ARG NEXT_PUBLIC_CUKIES_BRIDGE_TRON_NETWORK
ARG NEXT_PUBLIC_CUKIES_BRIDGE_TRON_RPC_URL
ARG NEXT_PUBLIC_CUKIES_BRIDGE_TRON_COLLECTION_ADDRESS
ARG NEXT_PUBLIC_CUKIES_BRIDGE_TRON_ENDPOINT_ADDRESS
ARG NEXT_PUBLIC_BSCSCAN_BASE_URL
ARG NEXT_PUBLIC_UKI_PRESALE_START_ISO
ARG NEXT_PUBLIC_UKI_PRESALE_START_LABEL
ARG NEXT_PUBLIC_UKI_PRESALE_START_SHORT_LABEL
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID

ENV NEXT_TELEMETRY_DISABLED=1
ENV PNPM_HOME=/pnpm
ENV PATH="${PNPM_HOME}:${PATH}"
ENV NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
ENV NEXT_PUBLIC_UKI_CHAIN_ID=${NEXT_PUBLIC_UKI_CHAIN_ID}
ENV NEXT_PUBLIC_ASM_TOKEN_ADDRESS=${NEXT_PUBLIC_ASM_TOKEN_ADDRESS}
ENV NEXT_PUBLIC_UKI_TOKEN_ADDRESS=${NEXT_PUBLIC_UKI_TOKEN_ADDRESS}
ENV NEXT_PUBLIC_UKI_VESTING_VAULT_ADDRESS=${NEXT_PUBLIC_UKI_VESTING_VAULT_ADDRESS}
ENV NEXT_PUBLIC_UKI_PRESALE_ADDRESS=${NEXT_PUBLIC_UKI_PRESALE_ADDRESS}
ENV NEXT_PUBLIC_UKI_STAKING_ADDRESS=${NEXT_PUBLIC_UKI_STAKING_ADDRESS}
ENV NEXT_PUBLIC_UKI_REWARDS_DISTRIBUTOR_ADDRESS=${NEXT_PUBLIC_UKI_REWARDS_DISTRIBUTOR_ADDRESS}
ENV NEXT_PUBLIC_UKI_LIQUIDITY_PAIR_ADDRESS=${NEXT_PUBLIC_UKI_LIQUIDITY_PAIR_ADDRESS}
ENV NEXT_PUBLIC_UKI_LIQUIDITY_LOCKER_ADDRESS=${NEXT_PUBLIC_UKI_LIQUIDITY_LOCKER_ADDRESS}
ENV NEXT_PUBLIC_UKI_LIQUIDITY_UNLOCK_LABEL=${NEXT_PUBLIC_UKI_LIQUIDITY_UNLOCK_LABEL}
ENV NEXT_PUBLIC_UKI_SWAP_URL=${NEXT_PUBLIC_UKI_SWAP_URL}
ENV NEXT_PUBLIC_CUKIE_MASTER_NFT_VAULT_ADDRESS=${NEXT_PUBLIC_CUKIE_MASTER_NFT_VAULT_ADDRESS}
ENV NEXT_PUBLIC_CUKIE_POOL_NFT_VAULT_ADDRESS=${NEXT_PUBLIC_CUKIE_POOL_NFT_VAULT_ADDRESS}
ENV NEXT_PUBLIC_CUKIES_NFT_COLLECTION_ADDRESS=${NEXT_PUBLIC_CUKIES_NFT_COLLECTION_ADDRESS}
ENV NEXT_PUBLIC_CUKIES_NFT_COLLECTION_ADDRESSES=${NEXT_PUBLIC_CUKIES_NFT_COLLECTION_ADDRESSES}
ENV NEXT_PUBLIC_CUKIES_NFT_RECOVERY_COLLECTION_ADDRESSES=${NEXT_PUBLIC_CUKIES_NFT_RECOVERY_COLLECTION_ADDRESSES}
ENV NEXT_PUBLIC_CUKIES_BRIDGE_MODE=${NEXT_PUBLIC_CUKIES_BRIDGE_MODE}
ENV NEXT_PUBLIC_CUKIES_BRIDGE_BSC_CHAIN_ID=${NEXT_PUBLIC_CUKIES_BRIDGE_BSC_CHAIN_ID}
ENV NEXT_PUBLIC_CUKIES_BRIDGE_BSC_COLLECTION_ADDRESS=${NEXT_PUBLIC_CUKIES_BRIDGE_BSC_COLLECTION_ADDRESS}
ENV NEXT_PUBLIC_CUKIES_BRIDGE_BSC_ENDPOINT_ADDRESS=${NEXT_PUBLIC_CUKIES_BRIDGE_BSC_ENDPOINT_ADDRESS}
ENV NEXT_PUBLIC_CUKIES_BRIDGE_TRON_NETWORK=${NEXT_PUBLIC_CUKIES_BRIDGE_TRON_NETWORK}
ENV NEXT_PUBLIC_CUKIES_BRIDGE_TRON_RPC_URL=${NEXT_PUBLIC_CUKIES_BRIDGE_TRON_RPC_URL}
ENV NEXT_PUBLIC_CUKIES_BRIDGE_TRON_COLLECTION_ADDRESS=${NEXT_PUBLIC_CUKIES_BRIDGE_TRON_COLLECTION_ADDRESS}
ENV NEXT_PUBLIC_CUKIES_BRIDGE_TRON_ENDPOINT_ADDRESS=${NEXT_PUBLIC_CUKIES_BRIDGE_TRON_ENDPOINT_ADDRESS}
ENV NEXT_PUBLIC_BSCSCAN_BASE_URL=${NEXT_PUBLIC_BSCSCAN_BASE_URL}
ENV NEXT_PUBLIC_UKI_PRESALE_START_ISO=${NEXT_PUBLIC_UKI_PRESALE_START_ISO}
ENV NEXT_PUBLIC_UKI_PRESALE_START_LABEL=${NEXT_PUBLIC_UKI_PRESALE_START_LABEL}
ENV NEXT_PUBLIC_UKI_PRESALE_START_SHORT_LABEL=${NEXT_PUBLIC_UKI_PRESALE_START_SHORT_LABEL}
ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates openssl \
  && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@10.19.0 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY dapp/package.json dapp/package.json
COPY dapp/prisma dapp/prisma
COPY games/hyppie-road/package.json games/hyppie-road/package.json
COPY games/sybil-slayer/package.json games/sybil-slayer/package.json
COPY games/tower-builder/package.json games/tower-builder/package.json
COPY packages/chain-indexer/package.json packages/chain-indexer/package.json
COPY packages/contracts/package.json packages/contracts/package.json
COPY packages/cuki-card-worker/package.json packages/cuki-card-worker/package.json
COPY packages/cukies-bridge-relayer/package.json packages/cukies-bridge-relayer/package.json
COPY packages/game-bridge/package.json packages/game-bridge/package.json

RUN pnpm install --frozen-lockfile

COPY . .

RUN if [ "$CUKIES_SERVICE" = "dapp" ]; then \
      pnpm --filter dapp build; \
    elif [ "$CUKIES_SERVICE" = "chain-indexer" ]; then \
      pnpm --filter @cukies/chain-indexer run build; \
    elif [ "$CUKIES_SERVICE" = "cuki-card-worker" ]; then \
      pnpm --filter @cukies/cuki-card-worker run build; \
    elif [ "$CUKIES_SERVICE" = "cukies-bridge-relayer" ]; then \
      pnpm --filter @cukies/cukies-bridge-relayer run build; \
    else \
      echo "CUKIES_SERVICE no soportado: $CUKIES_SERVICE" && exit 1; \
    fi

ENV NODE_ENV=production

EXPOSE 3000

CMD ["sh", "scripts/docker-start.sh"]
