export const UKI_PRESALE_START_ISO = process.env.NEXT_PUBLIC_UKI_PRESALE_START_ISO || '2026-06-15T00:00:00+02:00';
export const UKI_PRESALE_HAS_EXACT_START = Boolean(UKI_PRESALE_START_ISO);
export const UKI_PRESALE_START_LABEL = process.env.NEXT_PUBLIC_UKI_PRESALE_START_LABEL || '15 de junio de 2026';
export const UKI_PRESALE_START_SHORT_LABEL = process.env.NEXT_PUBLIC_UKI_PRESALE_START_SHORT_LABEL || '15 de junio';
export const UKI_PRESALE_CHAIN_ID = Number(process.env.NEXT_PUBLIC_UKI_CHAIN_ID || 56);
export const UKI_PRESALE_CHAIN_LABEL = UKI_PRESALE_CHAIN_ID === 97 ? 'BNB Smart Chain Testnet' : 'BNB Smart Chain';
