export const WEEKLY_RANKING_COLLECTIONS = [
  "weekly_ranking_rule_state",
  "weekly_ranking_period_states",
  "weekly_ranking_sources",
  "weekly_ranking_manifests",
  "weekly_ranking_runs",
  "weekly_ranking_audit_events",
  "weekly_ranking_runtime_state",
  "weekly_ranking_runtime_runs",
  "game_weekly_rankings",
] as const;

export const WEEKLY_RANKING_INDEX_DEFINITIONS = [
  { collection: "weekly_ranking_rule_state", keys: { scope: 1, revision: 1 }, options: { unique: true, name: "weekly_ranking_rule_fence" } },
  { collection: "weekly_ranking_period_states", keys: { periodId: 1 }, options: { unique: true, name: "weekly_ranking_period_state" } },
  { collection: "weekly_ranking_sources", keys: { sourceId: 1 }, options: { unique: true, name: "weekly_ranking_source_id" } },
  { collection: "weekly_ranking_sources", keys: { periodId: 1, _id: 1 }, options: { name: "weekly_ranking_source_period_cursor" } },
  { collection: "weekly_ranking_sources", keys: { periodId: 1, gameId: 1, walletNormalized: 1, _id: 1 }, options: { name: "weekly_ranking_source_participant_cursor" } },
  { collection: "weekly_ranking_sources", keys: { sessionId: 1 }, options: { unique: true, name: "weekly_ranking_source_session" } },
  { collection: "weekly_ranking_manifests", keys: { periodId: 1 }, options: { unique: true, name: "weekly_ranking_manifest_period" } },
  { collection: "weekly_ranking_manifests", keys: { manifestId: 1 }, options: { unique: true, name: "weekly_ranking_manifest_id" } },
  { collection: "weekly_ranking_runs", keys: { periodId: 1 }, options: { unique: true, name: "weekly_ranking_run_period" } },
  { collection: "weekly_ranking_runs", keys: { runId: 1 }, options: { unique: true, name: "weekly_ranking_run_id" } },
  { collection: "weekly_ranking_audit_events", keys: { eventId: 1 }, options: { unique: true, name: "weekly_ranking_audit_event_id" } },
  { collection: "weekly_ranking_audit_events", keys: { periodId: 1, createdAt: 1, _id: 1 }, options: { name: "weekly_ranking_audit_period_cursor" } },
  { collection: "weekly_ranking_runtime_state", keys: { updatedAt: -1 }, options: { name: "weekly_ranking_runtime_health" } },
  { collection: "weekly_ranking_runtime_state", keys: { schedulerId: 1, lastAttemptAt: -1 }, options: { name: "weekly_ranking_scheduler_heartbeat" } },
  { collection: "weekly_ranking_runtime_runs", keys: { status: 1, endedAt: -1 }, options: { name: "weekly_ranking_runtime_run_health" } },
  { collection: "weekly_ranking_runtime_runs", keys: { expiresAt: 1 }, options: { expireAfterSeconds: 0, name: "weekly_ranking_runtime_run_expiry" } },
  { collection: "game_weekly_rankings", keys: { rankingId: 1 }, options: { unique: true, name: "game_weekly_ranking_id" } },
  { collection: "game_weekly_rankings", keys: { periodId: 1, gameId: 1, walletNormalized: 1 }, options: { unique: true, name: "game_weekly_ranking_wallet_period" } },
  { collection: "game_weekly_rankings", keys: { gameId: 1, walletNormalized: 1, periodStart: -1, _id: -1 }, options: { name: "game_weekly_ranking_previous" } },
  { collection: "game_weekly_rankings", keys: { periodId: 1, status: 1, rank: 1, _id: 1 }, options: { name: "game_weekly_ranking_period_cursor" } },
] as const;
